### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [roperzh/tinyce-hugo-theme#20]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:
![image](https://user-images.githubusercontent.com/712534/37676117-16e1c044-2c88-11e8-94d6-5d8d687e413b.png)

Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by roperzh** [comment]
Thanks for the report! Fixed in #21 courtesy of @nonumeros  :)
